export const Country = [
    {value: '', key: 'Afghanistan', text: 'AF'},
    {value: '', key: 'Åland Islands', text: 'AX'},
    {value: '', key: 'Albania', text: 'AL'},
    {value: '', key: 'Algeria', text: 'DZ'},
    {value: '', key: 'American Samoa', text: 'AS'},
    {value: '', key: 'AndorrA', text: 'AD'},
    {value: '', key: 'Angola', text: 'AO'},
    {value: '', key: 'Anguilla', text: 'AI'},
    {value: '', key: 'Antarctica', text: 'AQ'},
    {value: '', key: 'Antigua and Barbuda', text: 'AG'},
    {value: '', key: 'Argentina', text: 'AR'},
    {value: '', key: 'Armenia', text: 'AM'},
    {value: '', key: 'Aruba', text: 'AW'},
    {value: '', key: 'Australia', text: 'AU'},
    {value: '', key: 'Austria', text: 'AT'},
    {value: '', key: 'Azerbaijan', text: 'AZ'},
    {value: '', key: 'Bahamas', text: 'BS'},
    {value: '', key: 'Bahrain', text: 'BH'},
    {value: '', key: 'Bangladesh', text: 'BD'},
    {value: '', key: 'Barbados', text: 'BB'},
    {value: '', key: 'Belarus', text: 'BY'},
    {value: '', key: 'Belgium', text: 'BE'},
    {value: '', key: 'Belize', text: 'BZ'},
    {value: '', key: 'Benin', text: 'BJ'},
    {value: '', key: 'Bermuda', text: 'BM'},
    {value: '', key: 'Bhutan', text: 'BT'},
    {value: '', key: 'Bolivia', text: 'BO'},
    {value: '', key: 'Bosnia and Herzegovina', text: 'BA'},
    {value: '', key: 'Botswana', text: 'BW'},
    {value: '', key: 'Bouvet Island', text: 'BV'},
    {value: '', key: 'Brazil', text: 'BR'},
    {value: '', key: 'British Indian Ocean Territory', text: 'IO'},
    {value: '', key: 'Brunei Darussalam', text: 'BN'},
    {value: '', key: 'Bulgaria', text: 'BG'},
    {value: '', key: 'Burkina Faso', text: 'BF'},
    {value: '', key: 'Burundi', text: 'BI'},
    {value: '', key: 'Cambodia', text: 'KH'},
    {value: '', key: 'Cameroon', text: 'CM'},
    {value: '', key: 'Canada', text: 'CA'},
    {value: '', key: 'Cape Verde', text: 'CV'},
    {value: '', key: 'Cayman Islands', text: 'KY'},
    {value: '', key: 'Central African Republic', text: 'CF'},
    {value: '', key: 'Chad', text: 'TD'},
    {value: '', key: 'Chile', text: 'CL'},
    {value: '', key: 'China', text: 'CN'},
    {value: '', key: 'Christmas Island', text: 'CX'},
    {value: '', key: 'Cocos (Keeling) Islands', text: 'CC'},
    {value: '', key: 'Colombia', text: 'CO'},
    {value: '', key: 'Comoros', text: 'KM'},
    {value: '', key: 'Congo', text: 'CG'},
    {value: '', key: 'Congo, The Democratic Republic of the', text: 'CD'},
    {value: '', key: 'Cook Islands', text: 'CK'},
    {value: '', key: 'Costa Rica', text: 'CR'},
    {value: '', key: 'Cote DIvoire', text: 'CI'},
    {value: '', key: 'Croatia', text: 'HR'},
    {value: '', key: 'Cuba', text: 'CU'},
    {value: '', key: 'Cyprus', text: 'CY'},
    {value: '', key: 'Czech Republic', text: 'CZ'},
    {value: '', key: 'Denmark', text: 'DK'},
    {value: '', key: 'Djibouti', text: 'DJ'},
    {value: '', key: 'Dominica', text: 'DM'},
    {value: '', key: 'Dominican Republic', text: 'DO'},
    {value: '', key: 'Ecuador', text: 'EC'},
    {value: '', key: 'Egypt', text: 'EG'},
    {value: '', key: 'El Salvador', text: 'SV'},
    {value: '', key: 'Equatorial Guinea', text: 'GQ'},
    {value: '', key: 'Eritrea', text: 'ER'},
    {value: '', key: 'Estonia', text: 'EE'},
    {value: '', key: 'Ethiopia', text: 'ET'},
    {value: '', key: 'Falkland Islands (Malvinas)', text: 'FK'},
    {value: '', key: 'Faroe Islands', text: 'FO'},
    {value: '', key: 'Fiji', text: 'FJ'},
    {value: '', key: 'Finland', text: 'FI'},
    {value: '', key: 'France', text: 'FR'},
    {value: '', key: 'French Guiana', text: 'GF'},
    {value: '', key: 'French Polynesia', text: 'PF'},
    {value: '', key: 'French Southern Territories', text: 'TF'},
    {value: '', key: 'Gabon', text: 'GA'},
    {value: '', key: 'Gambia', text: 'GM'},
    {value: '', key: 'Georgia', text: 'GE'},
    {value: '', key: 'Germany', text: 'DE'},
    {value: '', key: 'Ghana', text: 'GH'},
    {value: '', key: 'Gibraltar', text: 'GI'},
    {value: '', key: 'Greece', text: 'GR'},
    {value: '', key: 'Greenland', text: 'GL'},
    {value: '', key: 'Grenada', text: 'GD'},
    {value: '', key: 'Guadeloupe', text: 'GP'},
    {value: '', key: 'Guam', text: 'GU'},
    {value: '', key: 'Guatemala', text: 'GT'},
    {value: '', key: 'Guernsey', text: 'GG'},
    {value: '', key: 'Guinea', text: 'GN'},
    {value: '', key: 'Guinea-Bissau', text: 'GW'},
    {value: '', key: 'Guyana', text: 'GY'},
    {value: '', key: 'Haiti', text: 'HT'},
    {value: '', key: 'Heard Island and Mcdonald Islands', text: 'HM'},
    {value: '', key: 'Holy See (Vatican City State)', text: 'VA'},
    {value: '', key: 'Honduras', text: 'HN'},
    {value: '', key: 'Hong Kong', text: 'HK'},
    {value: '', key: 'Hungary', text: 'HU'},
    {value: '', key: 'Iceland', text: 'IS'},
    {value: '', key: 'India', text: 'IN'},
    {value: '', key: 'Indonesia', text: 'ID'},
    {value: '', key: 'Iran, Islamic Republic Of', text: 'IR'},
    {value: '', key: 'Iraq', text: 'IQ'},
    {value: '', key: 'Ireland', text: 'IE'},
    {value: '', key: 'Isle of Man', text: 'IM'},
    {value: '', key: 'Israel', text: 'IL'},
    {value: '', key: 'Italy', text: 'IT'},
    {value: '', key: 'Jamaica', text: 'JM'},
    {value: '', key: 'Japan', text: 'JP'},
    {value: '', key: 'Jersey', text: 'JE'},
    {value: '', key: 'Jordan', text: 'JO'},
    {value: '', key: 'Kazakhstan', text: 'KZ'},
    {value: '', key: 'Kenya', text: 'KE'},
    {value: '', key: 'Kiribati', text: 'KI'},
    {value: '', key: 'Korea, Democratic Peoples Republic of', text: 'KP'},
    {value: '', key: 'Korea, Republic of', text: 'KR'},
    {value: '', key: 'Kuwait', text: 'KW'},
    {value: '', key: 'Kyrgyzstan', text: 'KG'},
    {value: '', key: 'Lao Peoples Democratic Republic', text: 'LA'},
    {value: '', key: 'Latvia', text: 'LV'},
    {value: '', key: 'Lebanon', text: 'LB'},
    {value: '', key: 'Lesotho', text: 'LS'},
    {value: '', key: 'Liberia', text: 'LR'},
    {value: '', key: 'Libyan Arab Jamahiriya', text: 'LY'},
    {value: '', key: 'Liechtenstein', text: 'LI'},
    {value: '', key: 'Lithuania', text: 'LT'},
    {value: '', key: 'Luxembourg', text: 'LU'},
    {value: '', key: 'Macao', text: 'MO'},
    {value: '', key: 'Macedonia, The Former Yugoslav Republic of', text: 'MK'},
    {value: '', key: 'Madagascar', text: 'MG'},
    {value: '', key: 'Malawi', text: 'MW'},
    {value: '', key: 'Malaysia', text: 'MY'},
    {value: '', key: 'Maldives', text: 'MV'},
    {value: '', key: 'Mali', text: 'ML'},
    {value: '', key: 'Malta', text: 'MT'},
    {value: '', key: 'Marshall Islands', text: 'MH'},
    {value: '', key: 'Martinique', text: 'MQ'},
    {value: '', key: 'Mauritania', text: 'MR'},
    {value: '', key: 'Mauritius', text: 'MU'},
    {value: '', key: 'Mayotte', text: 'YT'},
    {value: '', key: 'Mexico', text: 'MX'},
    {value: '', key: 'Micronesia, Federated States of', text: 'FM'},
    {value: '', key: 'Moldova, Republic of', text: 'MD'},
    {value: '', key: 'Monaco', text: 'MC'},
    {value: '', key: 'Mongolia', text: 'MN'},
    {value: '', key: 'Montserrat', text: 'MS'},
    {value: '', key: 'Morocco', text: 'MA'},
    {value: '', key: 'Mozambique', text: 'MZ'},
    {value: '', key: 'Myanmar', text: 'MM'},
    {value: '', key: 'Namibia', text: 'NA'},
    {value: '', key: 'Nauru', text: 'NR'},
    {value: '', key: 'Nepal', text: 'NP'},
    {value: '', key: 'Netherlands', text: 'NL'},
    {value: '', key: 'Netherlands Antilles', text: 'AN'},
    {value: '', key: 'New Caledonia', text: 'NC'},
    {value: '', key: 'New Zealand', text: 'NZ'},
    {value: '', key: 'Nicaragua', text: 'NI'},
    {value: '', key: 'Niger', text: 'NE'},
    {value: '', key: 'Nigeria', text: 'NG'},
    {value: '', key: 'Niue', text: 'NU'},
    {value: '', key: 'Norfolk Island', text: 'NF'},
    {value: '', key: 'Northern Mariana Islands', text: 'MP'},
    {value: '', key: 'Norway', text: 'NO'},
    {value: '', key: 'Oman', text: 'OM'},
    {value: '', key: 'Pakistan', text: 'PK'},
    {value: '', key: 'Palau', text: 'PW'},
    {value: '', key: 'Palestinian Territory, Occupied', text: 'PS'},
    {value: '', key: 'Panama', text: 'PA'},
    {value: '', key: 'Papua New Guinea', text: 'PG'},
    {value: '', key: 'Paraguay', text: 'PY'},
    {value: '', key: 'Peru', text: 'PE'},
    {value: '', key: 'Philippines', text: 'PH'},
    {value: '', key: 'Pitcairn', text: 'PN'},
    {value: '', key: 'Poland', text: 'PL'},
    {value: '', key: 'Portugal', text: 'PT'},
    {value: '', key: 'Puerto Rico', text: 'PR'},
    {value: '', key: 'Qatar', text: 'QA'},
    {value: '', key: 'Reunion', text: 'RE'},
    {value: '', key: 'Romania', text: 'RO'},
    {value: '', key: 'Russian Federation', text: 'RU'},
    {value: '', key: 'RWANDA', text: 'RW'},
    {value: '', key: 'Saint Helena', text: 'SH'},
    {value: '', key: 'Saint Kitts and Nevis', text: 'KN'},
    {value: '', key: 'Saint Lucia', text: 'LC'},
    {value: '', key: 'Saint Pierre and Miquelon', text: 'PM'},
    {value: '', key: 'Saint Vincent and the Grenadines', text: 'VC'},
    {value: '', key: 'Samoa', text: 'WS'},
    {value: '', key: 'San Marino', text: 'SM'},
    {value: '', key: 'Sao Tome and Principe', text: 'ST'},
    {value: '', key: 'Saudi Arabia', text: 'SA'},
    {value: '', key: 'Senegal', text: 'SN'},
    {value: '', key: 'Serbia and Montenegro', text: 'CS'},
    {value: '', key: 'Seychelles', text: 'SC'},
    {value: '', key: 'Sierra Leone', text: 'SL'},
    {value: '', key: 'Singapore', text: 'SG'},
    {value: '', key: 'Slovakia', text: 'SK'},
    {value: '', key: 'Slovenia', text: 'SI'},
    {value: '', key: 'Solomon Islands', text: 'SB'},
    {value: '', key: 'Somalia', text: 'SO'},
    {value: '', key: 'South Africa', text: 'ZA'},
    {value: '', key: 'South Georgia and the South Sandwich Islands', text: 'GS'},
    {value: '', key: 'Spain', text: 'ES'},
    {value: '', key: 'Sri Lanka', text: 'LK'},
    {value: '', key: 'Sudan', text: 'SD'},
    {value: '', key: 'Suriname', text: 'SR'},
    {value: '', key: 'Svalbard and Jan Mayen', text: 'SJ'},
    {value: '', key: 'Swaziland', text: 'SZ'},
    {value: '', key: 'Sweden', text: 'SE'},
    {value: '', key: 'Switzerland', text: 'CH'},
    {value: '', key: 'Syrian Arab Republic', text: 'SY'},
    {value: '', key: 'Taiwan, Province of China', text: 'TW'},
    {value: '', key: 'Tajikistan', text: 'TJ'},
    {value: '', key: 'Tanzania, United Republic of', text: 'TZ'},
    {value: '', key: 'Thailand', text: 'TH'},
    {value: '', key: 'Timor-Leste', text: 'TL'},
    {value: '', key: 'Togo', text: 'TG'},
    {value: '', key: 'Tokelau', text: 'TK'},
    {value: '', key: 'Tonga', text: 'TO'},
    {value: '', key: 'Trinidad and Tobago', text: 'TT'},
    {value: '', key: 'Tunisia', text: 'TN'},
    {value: '', key: 'Turkey', text: 'TR'},
    {value: '', key: 'Turkmenistan', text: 'TM'},
    {value: '', key: 'Turks and Caicos Islands', text: 'TC'},
    {value: '', key: 'Tuvalu', text: 'TV'},
    {value: '', key: 'Uganda', text: 'UG'},
    {value: '', key: 'Ukraine', text: 'UA'},
    {value: '', key: 'United Arab Emirates', text: 'AE'},
    {value: '', key: 'United Kingdom', text: 'GB'},
    {value: '', key: 'United States', text: 'US'},
    {value: '', key: 'United States Minor Outlying Islands', text: 'UM'},
    {value: '', key: 'Uruguay', text: 'UY'},
    {value: '', key: 'Uzbekistan', text: 'UZ'},
    {value: '', key: 'Vanuatu', text: 'VU'},
    {value: '', key: 'Venezuela', text: 'VE'},
    {value: '', key: 'Viet Nam', text: 'VN'},
    {value: '', key: 'Virgin Islands, British', text: 'VG'},
    {value: '', key: 'Virgin Islands, U.S.', text: 'VI'},
    {value: '', key: 'Wallis and Futuna', text: 'WF'},
    {value: '', key: 'Western Sahara', text: 'EH'},
    {value: '', key: 'Yemen', text: 'YE'},
    {value: '', key: 'Zambia', text: 'ZM'},
    {value: '', key: 'Zimbabwe', text: 'ZW'}
    ];


